// 반응 이모지 검색용 라이브러리. 각 이모지에 한글 키워드를 붙여서 검색 가능하게 한다.
// 기본으로 노출되는 이모지는 없다 — "+ 이모지"를 눌러 검색해서 고른 것만 그 자리에 하나씩 나타난다.

export type Category = 'face' | 'gesture' | 'animal' | 'food' | 'nature' | 'activity' | 'travel' | 'object' | 'work' | 'etc'

export type EmojiEntry = { emoji: string; keywords: string[]; category: Category }

export const EMOJI_CATEGORIES: { key: Category; label: string }[] = [
  { key: 'face', label: '표정' },
  { key: 'gesture', label: '손동작' },
  { key: 'animal', label: '동물' },
  { key: 'food', label: '음식' },
  { key: 'nature', label: '날씨' },
  { key: 'activity', label: '활동' },
  { key: 'travel', label: '이동·장소' },
  { key: 'object', label: '사물' },
  { key: 'work', label: '업무' },
  { key: 'etc', label: '기타' },
]

export const EMOJI_LIBRARY: EmojiEntry[] = [
  { emoji: '❤️', keywords: ['하트', '마음', '좋아요', '사랑'], category: 'face' },
  { emoji: '😂', keywords: ['웃음', 'ㅋㅋ', '폭소', '빵터짐'], category: 'face' },
  { emoji: '👍', keywords: ['좋아요', '따봉', '엄지'], category: 'face' },
  { emoji: '🎉', keywords: ['축하', '파티', '경축'], category: 'face' },
  { emoji: '🔥', keywords: ['불', '핫', '대박', '열정'], category: 'face' },
  { emoji: '👏', keywords: ['박수', '잘했어', '칭찬'], category: 'face' },
  { emoji: '🙌', keywords: ['만세', '축하', '환호'], category: 'face' },
  { emoji: '🙏', keywords: ['감사', '부탁', '기도'], category: 'face' },
  { emoji: '😮', keywords: ['놀람', '헐', '오'], category: 'face' },
  { emoji: '😢', keywords: ['슬픔', '눈물', '울음'], category: 'face' },
  { emoji: '😅', keywords: ['민망', '땀', '어색'], category: 'face' },
  { emoji: '🤔', keywords: ['고민', '생각', '음'], category: 'face' },
  { emoji: '😴', keywords: ['잠', '피곤', '졸림'], category: 'face' },
  { emoji: '🥳', keywords: ['파티', '생일', '축하'], category: 'face' },
  { emoji: '😎', keywords: ['쿨', '멋짐', '선글라스'], category: 'face' },
  { emoji: '💯', keywords: ['백점', '완벽', '만점'], category: 'face' },
  { emoji: '✅', keywords: ['체크', '완료', '확인'], category: 'face' },
  { emoji: '❌', keywords: ['엑스', '아니오', '취소'], category: 'face' },
  { emoji: '⭐', keywords: ['별', '최고', '스타'], category: 'face' },
  { emoji: '💪', keywords: ['파이팅', '근육', '힘내'], category: 'face' },
  { emoji: '🙄', keywords: ['어이없음', '눈굴림'], category: 'face' },
  { emoji: '😱', keywords: ['놀람', '충격', '헐'], category: 'face' },
  { emoji: '🤯', keywords: ['폭발', '대박', '멘붕'], category: 'face' },
  { emoji: '🥲', keywords: ['눈물', '웃음', '울먹'], category: 'face' },
  { emoji: '🤝', keywords: ['악수', '합의', '협업'], category: 'gesture' },
  { emoji: '✌️', keywords: ['브이', '평화', '손가락'], category: 'gesture' },
  { emoji: '🐾', keywords: ['발바닥', '동물', '고양이', '강아지'], category: 'animal' },
  { emoji: '🐶', keywords: ['강아지', '개', '동물'], category: 'animal' },
  { emoji: '🐱', keywords: ['고양이', '냥이', '동물'], category: 'animal' },
  { emoji: '🐻', keywords: ['곰', '동물'], category: 'animal' },
  { emoji: '🐼', keywords: ['판다', '동물'], category: 'animal' },
  { emoji: '🐰', keywords: ['토끼', '동물'], category: 'animal' },
  { emoji: '🦊', keywords: ['여우', '동물'], category: 'animal' },
  { emoji: '🐯', keywords: ['호랑이', '동물'], category: 'animal' },
  { emoji: '🐹', keywords: ['햄스터', '동물'], category: 'animal' },
  { emoji: '🐮', keywords: ['소', '동물'], category: 'animal' },
  { emoji: '🐨', keywords: ['코알라', '동물'], category: 'animal' },
  { emoji: '🐧', keywords: ['펭귄', '동물'], category: 'animal' },
  { emoji: '🦁', keywords: ['사자', '동물'], category: 'animal' },
  { emoji: '🐸', keywords: ['개구리', '동물'], category: 'animal' },
  { emoji: '☕', keywords: ['커피', '카페'], category: 'food' },
  { emoji: '🍕', keywords: ['피자', '음식'], category: 'food' },
  { emoji: '🍺', keywords: ['맥주', '술'], category: 'food' },
  { emoji: '🎂', keywords: ['케이크', '생일'], category: 'food' },

  // 표정/감정 추가
  { emoji: '😆', keywords: ['박장대소', '웃음', '하하'], category: 'face' },
  { emoji: '😁', keywords: ['씨익', '웃음', '기쁨'], category: 'face' },
  { emoji: '🙃', keywords: ['웃픔', '실없음', '아이러니'], category: 'face' },
  { emoji: '😏', keywords: ['능글', '씨익'], category: 'face' },
  { emoji: '😤', keywords: ['부글부글', '화남', '씩씩'], category: 'face' },
  { emoji: '😡', keywords: ['화남', '분노', '빡침'], category: 'face' },
  { emoji: '🥺', keywords: ['부탁', '애원', '간절'], category: 'face' },
  { emoji: '😭', keywords: ['엉엉', '폭풍눈물', '슬픔'], category: 'face' },
  { emoji: '🤩', keywords: ['반짝반짝', '감탄', '최고'], category: 'face' },
  { emoji: '😇', keywords: ['천사', '순수', '착함'], category: 'face' },
  { emoji: '🥴', keywords: ['어지러움', '취함', '몽롱'], category: 'face' },
  { emoji: '🤗', keywords: ['포옹', '안아줘', '반가움'], category: 'face' },
  { emoji: '😬', keywords: ['아뿔싸', '민망', '어색'], category: 'face' },
  { emoji: '🥱', keywords: ['하품', '피곤', '지루'], category: 'face' },
  { emoji: '🤤', keywords: ['군침', '먹고싶다'], category: 'face' },
  { emoji: '😋', keywords: ['맛있다', '냠냠'], category: 'face' },
  { emoji: '🤪', keywords: ['엉뚱', '장난'], category: 'face' },
  { emoji: '😳', keywords: ['당황', '부끄러움'], category: 'face' },
  { emoji: '🫠', keywords: ['녹아내림', '무너짐'], category: 'face' },
  { emoji: '🫡', keywords: ['경례', '알겠습니다', '넵'], category: 'face' },
  { emoji: '🤫', keywords: ['쉿', '비밀'], category: 'face' },
  { emoji: '🤭', keywords: ['실수', '웃참'], category: 'face' },
  { emoji: '🥶', keywords: ['추움', '얼음'], category: 'face' },
  { emoji: '🥵', keywords: ['더움', '땀'], category: 'face' },
  { emoji: '😐', keywords: ['무표정', '뜨악'], category: 'face' },
  { emoji: '🙂', keywords: ['미소', '괜찮음'], category: 'face' },
  { emoji: '🫶', keywords: ['하트손', '사랑'], category: 'gesture' },

  // 제스처/손동작
  { emoji: '👌', keywords: ['오케이', '좋아'], category: 'gesture' },
  { emoji: '🤙', keywords: ['콜', '연락해'], category: 'gesture' },
  { emoji: '👊', keywords: ['주먹', '화이팅'], category: 'gesture' },
  { emoji: '✊', keywords: ['파이팅', '주먹'], category: 'gesture' },
  { emoji: '🤞', keywords: ['행운', '기원'], category: 'gesture' },
  { emoji: '👋', keywords: ['안녕', '인사'], category: 'gesture' },
  { emoji: '🖐️', keywords: ['하이파이브', '손바닥'], category: 'gesture' },

  // 업무/오피스
  { emoji: '💼', keywords: ['일', '업무', '가방'], category: 'work' },
  { emoji: '📅', keywords: ['일정', '캘린더'], category: 'work' },
  { emoji: '📌', keywords: ['고정', '중요'], category: 'work' },
  { emoji: '📝', keywords: ['메모', '작성'], category: 'work' },
  { emoji: '📊', keywords: ['통계', '그래프'], category: 'work' },
  { emoji: '💻', keywords: ['노트북', '작업'], category: 'work' },
  { emoji: '📈', keywords: ['상승', '성장'], category: 'work' },
  { emoji: '📉', keywords: ['하락', '감소'], category: 'work' },
  { emoji: '🗓️', keywords: ['달력', '스케줄'], category: 'work' },
  { emoji: '✏️', keywords: ['연필', '작성'], category: 'work' },
  { emoji: '📎', keywords: ['첨부', '클립'], category: 'work' },
  { emoji: '🖨️', keywords: ['인쇄', '프린터'], category: 'work' },
  { emoji: '📞', keywords: ['전화', '연락'], category: 'work' },
  { emoji: '✉️', keywords: ['메일', '편지'], category: 'work' },
  { emoji: '🔖', keywords: ['북마크', '태그'], category: 'work' },

  // 음식/음료 추가
  { emoji: '🍜', keywords: ['라면', '국수'], category: 'food' },
  { emoji: '🍔', keywords: ['햄버거'], category: 'food' },
  { emoji: '🍟', keywords: ['감자튀김'], category: 'food' },
  { emoji: '🌮', keywords: ['타코'], category: 'food' },
  { emoji: '🍰', keywords: ['케이크', '조각케이크'], category: 'food' },
  { emoji: '🍩', keywords: ['도넛'], category: 'food' },
  { emoji: '🍫', keywords: ['초콜릿'], category: 'food' },
  { emoji: '🍿', keywords: ['팝콘'], category: 'food' },
  { emoji: '🥤', keywords: ['음료', '콜라'], category: 'food' },
  { emoji: '🍎', keywords: ['사과'], category: 'food' },
  { emoji: '🍊', keywords: ['귤'], category: 'food' },
  { emoji: '🍇', keywords: ['포도'], category: 'food' },
  { emoji: '🍉', keywords: ['수박'], category: 'food' },
  { emoji: '🍓', keywords: ['딸기'], category: 'food' },
  { emoji: '🥗', keywords: ['샐러드'], category: 'food' },
  { emoji: '🍱', keywords: ['도시락'], category: 'food' },
  { emoji: '🍙', keywords: ['주먹밥'], category: 'food' },
  { emoji: '🍣', keywords: ['초밥'], category: 'food' },
  { emoji: '🍦', keywords: ['아이스크림'], category: 'food' },
  { emoji: '🧋', keywords: ['버블티'], category: 'food' },

  // 날씨/자연
  { emoji: '🌞', keywords: ['해', '맑음'], category: 'nature' },
  { emoji: '🌧️', keywords: ['비'], category: 'nature' },
  { emoji: '❄️', keywords: ['눈', '겨울'], category: 'nature' },
  { emoji: '🌈', keywords: ['무지개'], category: 'nature' },
  { emoji: '🌙', keywords: ['달', '밤'], category: 'nature' },
  { emoji: '🌊', keywords: ['파도', '바다'], category: 'nature' },
  { emoji: '🌸', keywords: ['벚꽃', '봄'], category: 'nature' },
  { emoji: '🍀', keywords: ['네잎클로버', '행운'], category: 'nature' },
  { emoji: '🌻', keywords: ['해바라기'], category: 'nature' },
  { emoji: '🍁', keywords: ['단풍', '가을'], category: 'nature' },

  // 이동수단
  { emoji: '🚗', keywords: ['자동차', '차'], category: 'etc' },
  { emoji: '✈️', keywords: ['비행기', '여행'], category: 'etc' },
  { emoji: '🚀', keywords: ['로켓', '출발'], category: 'etc' },

  // 기호/사물
  { emoji: '💡', keywords: ['아이디어', '전구'], category: 'etc' },
  { emoji: '✨', keywords: ['반짝', '잘했어'], category: 'face' },
  { emoji: '⚡', keywords: ['번개', '빠름'], category: 'etc' },
  { emoji: '🎯', keywords: ['목표', '정확'], category: 'work' },
  { emoji: '🏆', keywords: ['트로피', '우승'], category: 'face' },
  { emoji: '🎁', keywords: ['선물'], category: 'etc' },
  { emoji: '🔔', keywords: ['알림', '종'], category: 'etc' },
  { emoji: '🔒', keywords: ['잠금', '비밀'], category: 'etc' },
  { emoji: '🔑', keywords: ['열쇠', '해결'], category: 'etc' },
  { emoji: '🕐', keywords: ['시간', '시계'], category: 'etc' },
  { emoji: '📍', keywords: ['위치', '장소'], category: 'etc' },
  { emoji: '🚨', keywords: ['경고', '긴급'], category: 'etc' },
  { emoji: '🎈', keywords: ['풍선', '축하'], category: 'face' },

  // 동물 추가
  { emoji: '🐴', keywords: ['말', '동물'], category: 'animal' },
  { emoji: '🐷', keywords: ['돼지', '동물'], category: 'animal' },
  { emoji: '🐔', keywords: ['닭', '동물'], category: 'animal' },
  { emoji: '🐢', keywords: ['거북이', '동물'], category: 'animal' },
  { emoji: '🐙', keywords: ['문어', '동물'], category: 'animal' },
  { emoji: '🦄', keywords: ['유니콘', '동물'], category: 'animal' },
  { emoji: '🐦', keywords: ['새', '동물'], category: 'animal' },
  { emoji: '🐝', keywords: ['벌', '동물'], category: 'animal' },
  { emoji: '🦋', keywords: ['나비', '동물'], category: 'animal' },

  // ── 노션/슬랙 참고 확장 ──────────────────────────────

  // 표정/감정 추가 2
  { emoji: '😀', keywords: ['웃음', '기본미소'], category: 'face' },
  { emoji: '😃', keywords: ['웃음', '기쁨'], category: 'face' },
  { emoji: '😄', keywords: ['웃음', '활짝'], category: 'face' },
  { emoji: '😊', keywords: ['미소', '흐뭇'], category: 'face' },
  { emoji: '☺️', keywords: ['미소', '수줍음'], category: 'face' },
  { emoji: '😍', keywords: ['하트눈', '반함', '최고'], category: 'face' },
  { emoji: '🥰', keywords: ['사랑', '하트', '설렘'], category: 'face' },
  { emoji: '😘', keywords: ['뽀뽀', '사랑'], category: 'face' },
  { emoji: '😙', keywords: ['뽀뽀', '미소'], category: 'face' },
  { emoji: '😚', keywords: ['뽀뽀', '수줍음'], category: 'face' },
  { emoji: '😗', keywords: ['뽀뽀', '휘파람'], category: 'face' },
  { emoji: '🤑', keywords: ['돈', '대박', '머니'], category: 'face' },
  { emoji: '😒', keywords: ['시큰둥', '뚱함'], category: 'face' },
  { emoji: '😔', keywords: ['우울', '풀죽음'], category: 'face' },
  { emoji: '😞', keywords: ['실망', '낙담'], category: 'face' },
  { emoji: '😟', keywords: ['걱정', '근심'], category: 'face' },
  { emoji: '😕', keywords: ['찝찝', '갸우뚱'], category: 'face' },
  { emoji: '🙁', keywords: ['속상', '찡그림'], category: 'face' },
  { emoji: '☹️', keywords: ['슬픔', '찡그림'], category: 'face' },
  { emoji: '😣', keywords: ['괴로움', '끙'], category: 'face' },
  { emoji: '😖', keywords: ['곤란', '괴로움'], category: 'face' },
  { emoji: '😩', keywords: ['지침', '힘듦'], category: 'face' },
  { emoji: '😫', keywords: ['탈진', '피곤'], category: 'face' },
  { emoji: '🤨', keywords: ['의심', '한쪽눈썹'], category: 'face' },
  { emoji: '😑', keywords: ['무표정', '할말없음'], category: 'face' },
  { emoji: '🫥', keywords: ['투명', '존재감없음'], category: 'face' },
  { emoji: '🥹', keywords: ['울컥', '감동'], category: 'face' },
  { emoji: '🤓', keywords: ['안경', '너드'], category: 'face' },
  { emoji: '🧐', keywords: ['모니클', '분석'], category: 'face' },
  { emoji: '😷', keywords: ['마스크', '아픔'], category: 'face' },
  { emoji: '🤒', keywords: ['열', '아픔'], category: 'face' },
  { emoji: '🤕', keywords: ['부상', '다침'], category: 'face' },
  { emoji: '🤮', keywords: ['구토', '토함'], category: 'face' },
  { emoji: '🤧', keywords: ['재채기', '감기'], category: 'face' },
  { emoji: '🥸', keywords: ['변장', '위장'], category: 'face' },
  { emoji: '🫤', keywords: ['애매', '떨떠름'], category: 'face' },
  { emoji: '💀', keywords: ['해골', '죽음', '빡침'], category: 'face' },
  { emoji: '👻', keywords: ['유령', '귀신'], category: 'face' },
  { emoji: '🤡', keywords: ['광대', '어이없음'], category: 'face' },
  { emoji: '💩', keywords: ['똥', '망함'], category: 'face' },
  { emoji: '😈', keywords: ['악마', '장난'], category: 'face' },
  { emoji: '👿', keywords: ['악마', '분노'], category: 'face' },
  { emoji: '🤖', keywords: ['로봇', 'AI'], category: 'face' },
  { emoji: '👽', keywords: ['외계인'], category: 'face' },

  // 손동작 추가 2
  { emoji: '👎', keywords: ['별로', '싫어요'], category: 'gesture' },
  { emoji: '🤛', keywords: ['주먹인사'], category: 'gesture' },
  { emoji: '🤜', keywords: ['주먹인사'], category: 'gesture' },
  { emoji: '🫰', keywords: ['머니사인', '딱'], category: 'gesture' },
  { emoji: '🖖', keywords: ['인사', '스팍'], category: 'gesture' },
  { emoji: '🤌', keywords: ['이게뭐야', '손모음'], category: 'gesture' },
  { emoji: '🤟', keywords: ['사랑해', '락'], category: 'gesture' },
  { emoji: '👇', keywords: ['아래', '가리킴'], category: 'gesture' },
  { emoji: '👆', keywords: ['위', '가리킴'], category: 'gesture' },
  { emoji: '👉', keywords: ['오른쪽', '가리킴'], category: 'gesture' },
  { emoji: '👈', keywords: ['왼쪽', '가리킴'], category: 'gesture' },
  { emoji: '✋', keywords: ['멈춤', '손바닥'], category: 'gesture' },
  { emoji: '🤚', keywords: ['손등', '거절'], category: 'gesture' },
  { emoji: '👐', keywords: ['벌린손', '환영'], category: 'gesture' },
  { emoji: '🤲', keywords: ['받들기', '부탁'], category: 'gesture' },

  // 동물 추가 2
  { emoji: '🐺', keywords: ['늑대', '동물'], category: 'animal' },
  { emoji: '🦉', keywords: ['부엉이', '동물'], category: 'animal' },
  { emoji: '🐗', keywords: ['멧돼지', '동물'], category: 'animal' },
  { emoji: '🦓', keywords: ['얼룩말', '동물'], category: 'animal' },
  { emoji: '🦒', keywords: ['기린', '동물'], category: 'animal' },
  { emoji: '🐘', keywords: ['코끼리', '동물'], category: 'animal' },
  { emoji: '🦛', keywords: ['하마', '동물'], category: 'animal' },
  { emoji: '🦘', keywords: ['캥거루', '동물'], category: 'animal' },
  { emoji: '🐫', keywords: ['낙타', '동물'], category: 'animal' },
  { emoji: '🦙', keywords: ['라마', '동물'], category: 'animal' },
  { emoji: '🐆', keywords: ['표범', '동물'], category: 'animal' },
  { emoji: '🦇', keywords: ['박쥐', '동물'], category: 'animal' },
  { emoji: '🐿️', keywords: ['다람쥐', '동물'], category: 'animal' },
  { emoji: '🦔', keywords: ['고슴도치', '동물'], category: 'animal' },
  { emoji: '🐌', keywords: ['달팽이', '동물'], category: 'animal' },
  { emoji: '🐞', keywords: ['무당벌레', '동물'], category: 'animal' },
  { emoji: '🦗', keywords: ['귀뚜라미', '동물'], category: 'animal' },
  { emoji: '🕷️', keywords: ['거미', '동물'], category: 'animal' },
  { emoji: '🦂', keywords: ['전갈', '동물'], category: 'animal' },
  { emoji: '🐍', keywords: ['뱀', '동물'], category: 'animal' },
  { emoji: '🐊', keywords: ['악어', '동물'], category: 'animal' },
  { emoji: '🦕', keywords: ['공룡', '동물'], category: 'animal' },
  { emoji: '🦖', keywords: ['공룡', '티라노'], category: 'animal' },
  { emoji: '🐬', keywords: ['돌고래', '동물'], category: 'animal' },
  { emoji: '🐳', keywords: ['고래', '동물'], category: 'animal' },
  { emoji: '🐋', keywords: ['고래', '동물'], category: 'animal' },
  { emoji: '🦈', keywords: ['상어', '동물'], category: 'animal' },
  { emoji: '🦦', keywords: ['수달', '동물'], category: 'animal' },
  { emoji: '🦥', keywords: ['나무늘보', '동물'], category: 'animal' },
  { emoji: '🦨', keywords: ['스컹크', '동물'], category: 'animal' },
  { emoji: '🦡', keywords: ['오소리', '동물'], category: 'animal' },
  { emoji: '🐭', keywords: ['생쥐', '동물'], category: 'animal' },
  { emoji: '🐁', keywords: ['쥐', '동물'], category: 'animal' },
  { emoji: '🐀', keywords: ['쥐', '동물'], category: 'animal' },
  { emoji: '🦃', keywords: ['칠면조', '동물'], category: 'animal' },
  { emoji: '🐓', keywords: ['수탉', '동물'], category: 'animal' },
  { emoji: '🦚', keywords: ['공작', '동물'], category: 'animal' },
  { emoji: '🦜', keywords: ['앵무새', '동물'], category: 'animal' },
  { emoji: '🦢', keywords: ['백조', '동물'], category: 'animal' },
  { emoji: '🦩', keywords: ['플라밍고', '동물'], category: 'animal' },
  { emoji: '🐇', keywords: ['토끼', '동물'], category: 'animal' },
  { emoji: '🦫', keywords: ['비버', '동물'], category: 'animal' },

  // 음식 추가 2
  { emoji: '🍝', keywords: ['파스타', '스파게티'], category: 'food' },
  { emoji: '🍛', keywords: ['카레'], category: 'food' },
  { emoji: '🍲', keywords: ['찌개', '전골'], category: 'food' },
  { emoji: '🥘', keywords: ['볶음', '요리'], category: 'food' },
  { emoji: '🍳', keywords: ['계란후라이', '요리'], category: 'food' },
  { emoji: '🥞', keywords: ['팬케이크'], category: 'food' },
  { emoji: '🧇', keywords: ['와플'], category: 'food' },
  { emoji: '🥐', keywords: ['크루아상', '빵'], category: 'food' },
  { emoji: '🍞', keywords: ['식빵', '빵'], category: 'food' },
  { emoji: '🥖', keywords: ['바게트', '빵'], category: 'food' },
  { emoji: '🥨', keywords: ['프레첼'], category: 'food' },
  { emoji: '🧀', keywords: ['치즈'], category: 'food' },
  { emoji: '🍖', keywords: ['고기', '갈비'], category: 'food' },
  { emoji: '🍗', keywords: ['치킨', '닭다리'], category: 'food' },
  { emoji: '🥩', keywords: ['고기', '스테이크'], category: 'food' },
  { emoji: '🥓', keywords: ['베이컨'], category: 'food' },
  { emoji: '🌭', keywords: ['핫도그'], category: 'food' },
  { emoji: '🥪', keywords: ['샌드위치'], category: 'food' },
  { emoji: '🥙', keywords: ['케밥', '랩'], category: 'food' },
  { emoji: '🧆', keywords: ['팔라펠', '완자'], category: 'food' },
  { emoji: '🥟', keywords: ['만두'], category: 'food' },
  { emoji: '🍤', keywords: ['새우튀김'], category: 'food' },
  { emoji: '🍢', keywords: ['오뎅', '어묵'], category: 'food' },
  { emoji: '🍡', keywords: ['경단', '디저트'], category: 'food' },
  { emoji: '🍧', keywords: ['빙수'], category: 'food' },
  { emoji: '🍨', keywords: ['아이스크림'], category: 'food' },
  { emoji: '🧁', keywords: ['컵케이크'], category: 'food' },
  { emoji: '🍮', keywords: ['푸딩'], category: 'food' },
  { emoji: '🍯', keywords: ['꿀'], category: 'food' },
  { emoji: '🍬', keywords: ['사탕'], category: 'food' },
  { emoji: '🍭', keywords: ['막대사탕'], category: 'food' },
  { emoji: '🥛', keywords: ['우유'], category: 'food' },
  { emoji: '🧃', keywords: ['주스팩'], category: 'food' },
  { emoji: '🍹', keywords: ['칵테일'], category: 'food' },
  { emoji: '🍸', keywords: ['마티니', '술'], category: 'food' },
  { emoji: '🍷', keywords: ['와인'], category: 'food' },
  { emoji: '🥂', keywords: ['건배', '샴페인'], category: 'food' },
  { emoji: '🍾', keywords: ['샴페인', '축하'], category: 'food' },
  { emoji: '🧊', keywords: ['얼음'], category: 'food' },
  { emoji: '🥥', keywords: ['코코넛'], category: 'food' },
  { emoji: '🍋', keywords: ['레몬'], category: 'food' },
  { emoji: '🍌', keywords: ['바나나'], category: 'food' },
  { emoji: '🍑', keywords: ['복숭아'], category: 'food' },
  { emoji: '🍒', keywords: ['체리'], category: 'food' },
  { emoji: '🍈', keywords: ['멜론'], category: 'food' },
  { emoji: '🍐', keywords: ['배'], category: 'food' },
  { emoji: '🍅', keywords: ['토마토'], category: 'food' },
  { emoji: '🥑', keywords: ['아보카도'], category: 'food' },
  { emoji: '🥦', keywords: ['브로콜리'], category: 'food' },
  { emoji: '🥬', keywords: ['배추', '채소'], category: 'food' },
  { emoji: '🥕', keywords: ['당근'], category: 'food' },
  { emoji: '🌽', keywords: ['옥수수'], category: 'food' },
  { emoji: '🥔', keywords: ['감자'], category: 'food' },
  { emoji: '🍠', keywords: ['고구마'], category: 'food' },
  { emoji: '🥜', keywords: ['땅콩'], category: 'food' },
  { emoji: '🌰', keywords: ['밤'], category: 'food' },
  { emoji: '🍄', keywords: ['버섯'], category: 'food' },

  // 날씨/자연 추가 2
  { emoji: '🌤️', keywords: ['구름조금', '맑음'], category: 'nature' },
  { emoji: '⛅', keywords: ['구름', '흐림'], category: 'nature' },
  { emoji: '🌥️', keywords: ['구름많음'], category: 'nature' },
  { emoji: '🌦️', keywords: ['소나기'], category: 'nature' },
  { emoji: '🌩️', keywords: ['번개', '천둥'], category: 'nature' },
  { emoji: '⛈️', keywords: ['천둥번개', '폭풍'], category: 'nature' },
  { emoji: '🌪️', keywords: ['태풍', '토네이도'], category: 'nature' },
  { emoji: '🌫️', keywords: ['안개'], category: 'nature' },
  { emoji: '🌬️', keywords: ['바람'], category: 'nature' },
  { emoji: '🌡️', keywords: ['온도', '체온'], category: 'nature' },
  { emoji: '☔', keywords: ['우산', '장마'], category: 'nature' },
  { emoji: '🌜', keywords: ['초승달'], category: 'nature' },
  { emoji: '🌛', keywords: ['반달'], category: 'nature' },
  { emoji: '🌝', keywords: ['보름달'], category: 'nature' },
  { emoji: '🌚', keywords: ['그믐달'], category: 'nature' },
  { emoji: '🌕', keywords: ['보름달'], category: 'nature' },
  { emoji: '🌖', keywords: ['달'], category: 'nature' },
  { emoji: '🌗', keywords: ['반달'], category: 'nature' },
  { emoji: '🌘', keywords: ['그믐달'], category: 'nature' },
  { emoji: '🌑', keywords: ['신월'], category: 'nature' },
  { emoji: '🌒', keywords: ['초승달'], category: 'nature' },
  { emoji: '🌓', keywords: ['반달'], category: 'nature' },
  { emoji: '🌔', keywords: ['달'], category: 'nature' },
  { emoji: '🌟', keywords: ['반짝별', '최고'], category: 'nature' },
  { emoji: '💫', keywords: ['어지러움', '반짝'], category: 'nature' },
  { emoji: '☄️', keywords: ['혜성', '별똥별'], category: 'nature' },
  { emoji: '🌍', keywords: ['지구'], category: 'nature' },
  { emoji: '🌎', keywords: ['지구'], category: 'nature' },
  { emoji: '🌏', keywords: ['지구'], category: 'nature' },
  { emoji: '🌵', keywords: ['선인장'], category: 'nature' },
  { emoji: '🌴', keywords: ['야자수'], category: 'nature' },
  { emoji: '🌳', keywords: ['나무'], category: 'nature' },
  { emoji: '🌲', keywords: ['나무', '소나무'], category: 'nature' },
  { emoji: '🍃', keywords: ['나뭇잎', '바람'], category: 'nature' },
  { emoji: '🌿', keywords: ['풀', '허브'], category: 'nature' },
  { emoji: '🌾', keywords: ['벼', '이삭'], category: 'nature' },
  { emoji: '🌺', keywords: ['하와이꽃', '히비스커스'], category: 'nature' },
  { emoji: '🌹', keywords: ['장미'], category: 'nature' },
  { emoji: '🌼', keywords: ['들꽃', '데이지'], category: 'nature' },
  { emoji: '🌷', keywords: ['튤립'], category: 'nature' },
  { emoji: '💐', keywords: ['꽃다발'], category: 'nature' },
  { emoji: '🪴', keywords: ['화분'], category: 'nature' },
  { emoji: '🍂', keywords: ['낙엽', '가을'], category: 'nature' },
  { emoji: '🌱', keywords: ['새싹'], category: 'nature' },

  // 활동 (신규 카테고리)
  { emoji: '⚽', keywords: ['축구'], category: 'activity' },
  { emoji: '🏀', keywords: ['농구'], category: 'activity' },
  { emoji: '🏈', keywords: ['미식축구'], category: 'activity' },
  { emoji: '⚾', keywords: ['야구'], category: 'activity' },
  { emoji: '🎾', keywords: ['테니스'], category: 'activity' },
  { emoji: '🏐', keywords: ['배구'], category: 'activity' },
  { emoji: '🏉', keywords: ['럭비'], category: 'activity' },
  { emoji: '🎱', keywords: ['당구'], category: 'activity' },
  { emoji: '🏓', keywords: ['탁구'], category: 'activity' },
  { emoji: '🏸', keywords: ['배드민턴'], category: 'activity' },
  { emoji: '🥊', keywords: ['복싱'], category: 'activity' },
  { emoji: '🥋', keywords: ['유도', '태권도'], category: 'activity' },
  { emoji: '⛳', keywords: ['골프'], category: 'activity' },
  { emoji: '🎣', keywords: ['낚시'], category: 'activity' },
  { emoji: '🎿', keywords: ['스키'], category: 'activity' },
  { emoji: '🏂', keywords: ['스노보드'], category: 'activity' },
  { emoji: '🏄', keywords: ['서핑'], category: 'activity' },
  { emoji: '🚴', keywords: ['자전거', '사이클'], category: 'activity' },
  { emoji: '🏋️', keywords: ['웨이트', '헬스'], category: 'activity' },
  { emoji: '🧘', keywords: ['명상', '요가'], category: 'activity' },
  { emoji: '🎨', keywords: ['그림', '팔레트'], category: 'activity' },
  { emoji: '🎭', keywords: ['연극', '가면'], category: 'activity' },
  { emoji: '🎬', keywords: ['영화', '클래퍼보드'], category: 'activity' },
  { emoji: '🎤', keywords: ['노래', '마이크'], category: 'activity' },
  { emoji: '🎧', keywords: ['음악', '헤드폰'], category: 'activity' },
  { emoji: '🎵', keywords: ['음표', '음악'], category: 'activity' },
  { emoji: '🎶', keywords: ['음표', '음악'], category: 'activity' },
  { emoji: '🎹', keywords: ['피아노'], category: 'activity' },
  { emoji: '🥁', keywords: ['드럼'], category: 'activity' },
  { emoji: '🎸', keywords: ['기타'], category: 'activity' },
  { emoji: '🎺', keywords: ['트럼펫'], category: 'activity' },
  { emoji: '🎷', keywords: ['색소폰'], category: 'activity' },
  { emoji: '🎻', keywords: ['바이올린'], category: 'activity' },
  { emoji: '🪗', keywords: ['아코디언'], category: 'activity' },
  { emoji: '🎮', keywords: ['게임', '컨트롤러'], category: 'activity' },
  { emoji: '🎲', keywords: ['주사위'], category: 'activity' },
  { emoji: '🃏', keywords: ['카드', '조커'], category: 'activity' },
  { emoji: '🎳', keywords: ['볼링'], category: 'activity' },
  { emoji: '🥇', keywords: ['금메달', '1등'], category: 'activity' },
  { emoji: '🥈', keywords: ['은메달', '2등'], category: 'activity' },
  { emoji: '🥉', keywords: ['동메달', '3등'], category: 'activity' },
  { emoji: '🏅', keywords: ['메달'], category: 'activity' },
  { emoji: '🎖️', keywords: ['훈장'], category: 'activity' },
  { emoji: '🏹', keywords: ['양궁'], category: 'activity' },
  { emoji: '🤺', keywords: ['펜싱'], category: 'activity' },
  { emoji: '🏊', keywords: ['수영'], category: 'activity' },
  { emoji: '🚵', keywords: ['산악자전거'], category: 'activity' },
  { emoji: '🧗', keywords: ['클라이밍', '등반'], category: 'activity' },
  { emoji: '🛹', keywords: ['스케이트보드'], category: 'activity' },
  { emoji: '🛼', keywords: ['롤러스케이트'], category: 'activity' },
  { emoji: '⛸️', keywords: ['아이스스케이트'], category: 'activity' },
  { emoji: '🥌', keywords: ['컬링'], category: 'activity' },

  // 이동·장소 (신규 카테고리)
  { emoji: '🚕', keywords: ['택시'], category: 'travel' },
  { emoji: '🚙', keywords: ['SUV', '차'], category: 'travel' },
  { emoji: '🚌', keywords: ['버스'], category: 'travel' },
  { emoji: '🚎', keywords: ['트롤리버스'], category: 'travel' },
  { emoji: '🏍️', keywords: ['오토바이'], category: 'travel' },
  { emoji: '🚲', keywords: ['자전거'], category: 'travel' },
  { emoji: '🛴', keywords: ['킥보드'], category: 'travel' },
  { emoji: '🚉', keywords: ['기차역'], category: 'travel' },
  { emoji: '🚄', keywords: ['고속열차', 'KTX'], category: 'travel' },
  { emoji: '🚅', keywords: ['고속열차', '신칸센'], category: 'travel' },
  { emoji: '🚆', keywords: ['기차'], category: 'travel' },
  { emoji: '🚊', keywords: ['트램'], category: 'travel' },
  { emoji: '🚢', keywords: ['배', '선박'], category: 'travel' },
  { emoji: '⛵', keywords: ['요트', '돛단배'], category: 'travel' },
  { emoji: '🚁', keywords: ['헬리콥터'], category: 'travel' },
  { emoji: '🛸', keywords: ['UFO'], category: 'travel' },
  { emoji: '🚂', keywords: ['증기기관차'], category: 'travel' },
  { emoji: '🚐', keywords: ['승합차'], category: 'travel' },
  { emoji: '🚑', keywords: ['구급차'], category: 'travel' },
  { emoji: '🚒', keywords: ['소방차'], category: 'travel' },
  { emoji: '🚓', keywords: ['경찰차'], category: 'travel' },
  { emoji: '🛺', keywords: ['툭툭'], category: 'travel' },
  { emoji: '🚜', keywords: ['트랙터'], category: 'travel' },
  { emoji: '🗽', keywords: ['자유의여신상'], category: 'travel' },
  { emoji: '🗼', keywords: ['타워'], category: 'travel' },
  { emoji: '🏝️', keywords: ['무인도', '휴양'], category: 'travel' },
  { emoji: '🏔️', keywords: ['설산'], category: 'travel' },
  { emoji: '⛰️', keywords: ['산'], category: 'travel' },
  { emoji: '🏠', keywords: ['집'], category: 'travel' },
  { emoji: '🏢', keywords: ['빌딩', '사무실'], category: 'travel' },
  { emoji: '🏥', keywords: ['병원'], category: 'travel' },
  { emoji: '🏫', keywords: ['학교'], category: 'travel' },
  { emoji: '🏛️', keywords: ['관공서', '박물관'], category: 'travel' },
  { emoji: '⛪', keywords: ['교회'], category: 'travel' },
  { emoji: '🕌', keywords: ['모스크'], category: 'travel' },
  { emoji: '🗺️', keywords: ['지도'], category: 'travel' },
  { emoji: '🧳', keywords: ['여행가방'], category: 'travel' },
  { emoji: '🏕️', keywords: ['캠핑'], category: 'travel' },
  { emoji: '🏟️', keywords: ['경기장'], category: 'travel' },
  { emoji: '🎡', keywords: ['대관람차'], category: 'travel' },
  { emoji: '🎢', keywords: ['롤러코스터'], category: 'travel' },
  { emoji: '🎠', keywords: ['회전목마'], category: 'travel' },
  { emoji: '🌉', keywords: ['다리', '야경'], category: 'travel' },
  { emoji: '🗻', keywords: ['후지산'], category: 'travel' },

  // 사물 (신규 카테고리)
  { emoji: '⌚', keywords: ['손목시계'], category: 'object' },
  { emoji: '📱', keywords: ['휴대폰', '스마트폰'], category: 'object' },
  { emoji: '☎️', keywords: ['전화기'], category: 'object' },
  { emoji: '🔦', keywords: ['손전등'], category: 'object' },
  { emoji: '🕯️', keywords: ['양초'], category: 'object' },
  { emoji: '💊', keywords: ['약'], category: 'object' },
  { emoji: '🩹', keywords: ['반창고'], category: 'object' },
  { emoji: '🧬', keywords: ['DNA', '유전자'], category: 'object' },
  { emoji: '🔭', keywords: ['망원경'], category: 'object' },
  { emoji: '🔬', keywords: ['현미경'], category: 'object' },
  { emoji: '🧪', keywords: ['시험관', '실험'], category: 'object' },
  { emoji: '🔗', keywords: ['링크', '연결'], category: 'object' },
  { emoji: '🖇️', keywords: ['클립'], category: 'object' },
  { emoji: '🧷', keywords: ['옷핀'], category: 'object' },
  { emoji: '🖥️', keywords: ['모니터', '컴퓨터'], category: 'object' },
  { emoji: '⌨️', keywords: ['키보드'], category: 'object' },
  { emoji: '🖱️', keywords: ['마우스'], category: 'object' },
  { emoji: '💾', keywords: ['디스켓', '저장'], category: 'object' },
  { emoji: '💿', keywords: ['CD'], category: 'object' },
  { emoji: '📡', keywords: ['위성', '안테나'], category: 'object' },
  { emoji: '🔋', keywords: ['배터리'], category: 'object' },
  { emoji: '🔌', keywords: ['플러그', '충전'], category: 'object' },
  { emoji: '💰', keywords: ['돈주머니'], category: 'object' },
  { emoji: '💵', keywords: ['지폐', '돈'], category: 'object' },
  { emoji: '💳', keywords: ['카드', '결제'], category: 'object' },
  { emoji: '🏦', keywords: ['은행'], category: 'object' },
  { emoji: '📮', keywords: ['우체통'], category: 'object' },
  { emoji: '📦', keywords: ['택배', '상자'], category: 'object' },
  { emoji: '🔧', keywords: ['렌치', '수리'], category: 'object' },
  { emoji: '🔨', keywords: ['망치'], category: 'object' },
  { emoji: '🛠️', keywords: ['공구'], category: 'object' },
  { emoji: '⚙️', keywords: ['톱니바퀴', '설정'], category: 'object' },
  { emoji: '🧰', keywords: ['공구함'], category: 'object' },
  { emoji: '🪛', keywords: ['드라이버'], category: 'object' },
  { emoji: '🧲', keywords: ['자석'], category: 'object' },
  { emoji: '🕶️', keywords: ['선글라스'], category: 'object' },
  { emoji: '👓', keywords: ['안경'], category: 'object' },
  { emoji: '💍', keywords: ['반지'], category: 'object' },
  { emoji: '👑', keywords: ['왕관', '최고'], category: 'object' },
  { emoji: '🎀', keywords: ['리본'], category: 'object' },
  { emoji: '🧵', keywords: ['실'], category: 'object' },
  { emoji: '🧶', keywords: ['털실'], category: 'object' },

  // 업무 추가 2
  { emoji: '📚', keywords: ['책', '공부'], category: 'work' },
  { emoji: '📖', keywords: ['책', '읽기'], category: 'work' },
  { emoji: '🔍', keywords: ['검색', '돋보기'], category: 'work' },
  { emoji: '🔎', keywords: ['검색', '돋보기'], category: 'work' },
  { emoji: '📋', keywords: ['클립보드', '체크리스트'], category: 'work' },
  { emoji: '🗂️', keywords: ['파일함', '정리'], category: 'work' },
  { emoji: '🗃️', keywords: ['카드파일'], category: 'work' },
  { emoji: '🗄️', keywords: ['서류함'], category: 'work' },
  { emoji: '📁', keywords: ['폴더'], category: 'work' },
  { emoji: '📂', keywords: ['폴더열림'], category: 'work' },
  { emoji: '🗒️', keywords: ['메모장'], category: 'work' },
  { emoji: '🧾', keywords: ['영수증', '전표'], category: 'work' },
  { emoji: '🖊️', keywords: ['볼펜'], category: 'work' },
  { emoji: '🖋️', keywords: ['만년필'], category: 'work' },
  { emoji: '✂️', keywords: ['가위'], category: 'work' },
  { emoji: '📐', keywords: ['삼각자'], category: 'work' },
  { emoji: '📏', keywords: ['자'], category: 'work' },
  { emoji: '🧮', keywords: ['주판', '계산'], category: 'work' },

  // 기타 추가 2
  { emoji: '💤', keywords: ['졸림', '수면중'], category: 'etc' },
  { emoji: '‼️', keywords: ['강조', '느낌표'], category: 'etc' },
  { emoji: '❓', keywords: ['물음표', '궁금'], category: 'etc' },
  { emoji: '💢', keywords: ['화남', '분노'], category: 'etc' },
  { emoji: '💥', keywords: ['펑', '충돌'], category: 'etc' },
  { emoji: '💦', keywords: ['땀', '물방울'], category: 'etc' },
  { emoji: '💨', keywords: ['질주', '바람'], category: 'etc' },
  { emoji: '🎊', keywords: ['색종이', '축하'], category: 'etc' },
  { emoji: '🎏', keywords: ['잉어깃발', '축제'], category: 'etc' },
  { emoji: '🧨', keywords: ['폭죽'], category: 'etc' },
  { emoji: '🎆', keywords: ['불꽃놀이'], category: 'etc' },
  { emoji: '🎇', keywords: ['불꽃'], category: 'etc' },
  { emoji: '⏰', keywords: ['알람시계'], category: 'etc' },
  { emoji: '♻️', keywords: ['재활용'], category: 'etc' },
  { emoji: '⚠️', keywords: ['경고', '주의'], category: 'etc' },
  { emoji: '🚫', keywords: ['금지'], category: 'etc' },
  { emoji: '✔️', keywords: ['체크', '완료'], category: 'etc' },
  { emoji: '⬆️', keywords: ['위쪽화살표'], category: 'etc' },
  { emoji: '⬇️', keywords: ['아래쪽화살표'], category: 'etc' },
  { emoji: '➡️', keywords: ['오른쪽화살표'], category: 'etc' },
  { emoji: '⬅️', keywords: ['왼쪽화살표'], category: 'etc' },
]
