// 반응 이모지 검색용 라이브러리. 각 이모지에 한글 키워드를 붙여서 검색 가능하게 한다.
// 기본으로 노출되는 이모지는 없다 — "+ 이모지"를 눌러 검색해서 고른 것만 그 자리에 하나씩 나타난다.

export type EmojiEntry = { emoji: string; keywords: string[] }

export const EMOJI_LIBRARY: EmojiEntry[] = [
  { emoji: '❤️', keywords: ['하트', '마음', '좋아요', '사랑'] },
  { emoji: '😂', keywords: ['웃음', 'ㅋㅋ', '폭소', '빵터짐'] },
  { emoji: '👍', keywords: ['좋아요', '따봉', '엄지'] },
  { emoji: '🎉', keywords: ['축하', '파티', '경축'] },
  { emoji: '🔥', keywords: ['불', '핫', '대박', '열정'] },
  { emoji: '👏', keywords: ['박수', '잘했어', '칭찬'] },
  { emoji: '🙌', keywords: ['만세', '축하', '환호'] },
  { emoji: '🙏', keywords: ['감사', '부탁', '기도'] },
  { emoji: '😮', keywords: ['놀람', '헐', '오'] },
  { emoji: '😢', keywords: ['슬픔', '눈물', '울음'] },
  { emoji: '😅', keywords: ['민망', '땀', '어색'] },
  { emoji: '🤔', keywords: ['고민', '생각', '음'] },
  { emoji: '😴', keywords: ['잠', '피곤', '졸림'] },
  { emoji: '🥳', keywords: ['파티', '생일', '축하'] },
  { emoji: '😎', keywords: ['쿨', '멋짐', '선글라스'] },
  { emoji: '💯', keywords: ['백점', '완벽', '만점'] },
  { emoji: '✅', keywords: ['체크', '완료', '확인'] },
  { emoji: '❌', keywords: ['엑스', '아니오', '취소'] },
  { emoji: '⭐', keywords: ['별', '최고', '스타'] },
  { emoji: '💪', keywords: ['파이팅', '근육', '힘내'] },
  { emoji: '🙄', keywords: ['어이없음', '눈굴림'] },
  { emoji: '😱', keywords: ['놀람', '충격', '헐'] },
  { emoji: '🤯', keywords: ['폭발', '대박', '멘붕'] },
  { emoji: '🥲', keywords: ['눈물', '웃음', '울먹'] },
  { emoji: '🤝', keywords: ['악수', '합의', '협업'] },
  { emoji: '✌️', keywords: ['브이', '평화', '손가락'] },
  { emoji: '🐾', keywords: ['발바닥', '동물', '고양이', '강아지'] },
  { emoji: '🐶', keywords: ['강아지', '개', '동물'] },
  { emoji: '🐱', keywords: ['고양이', '냥이', '동물'] },
  { emoji: '🐻', keywords: ['곰', '동물'] },
  { emoji: '🐼', keywords: ['판다', '동물'] },
  { emoji: '🐰', keywords: ['토끼', '동물'] },
  { emoji: '🦊', keywords: ['여우', '동물'] },
  { emoji: '🐯', keywords: ['호랑이', '동물'] },
  { emoji: '🐹', keywords: ['햄스터', '동물'] },
  { emoji: '🐮', keywords: ['소', '동물'] },
  { emoji: '🐨', keywords: ['코알라', '동물'] },
  { emoji: '🐧', keywords: ['펭귄', '동물'] },
  { emoji: '🦁', keywords: ['사자', '동물'] },
  { emoji: '🐸', keywords: ['개구리', '동물'] },
  { emoji: '☕', keywords: ['커피', '카페'] },
  { emoji: '🍕', keywords: ['피자', '음식'] },
  { emoji: '🍺', keywords: ['맥주', '술'] },
  { emoji: '🎂', keywords: ['케이크', '생일'] },

  // 표정/감정 추가
  { emoji: '😆', keywords: ['박장대소', '웃음', '하하'] },
  { emoji: '😁', keywords: ['씨익', '웃음', '기쁨'] },
  { emoji: '🙃', keywords: ['웃픔', '실없음', '아이러니'] },
  { emoji: '😏', keywords: ['능글', '씨익'] },
  { emoji: '😤', keywords: ['부글부글', '화남', '씩씩'] },
  { emoji: '😡', keywords: ['화남', '분노', '빡침'] },
  { emoji: '🥺', keywords: ['부탁', '애원', '간절'] },
  { emoji: '😭', keywords: ['엉엉', '폭풍눈물', '슬픔'] },
  { emoji: '🤩', keywords: ['반짝반짝', '감탄', '최고'] },
  { emoji: '😇', keywords: ['천사', '순수', '착함'] },
  { emoji: '🥴', keywords: ['어지러움', '취함', '몽롱'] },
  { emoji: '🤗', keywords: ['포옹', '안아줘', '반가움'] },
  { emoji: '😬', keywords: ['아뿔싸', '민망', '어색'] },
  { emoji: '🥱', keywords: ['하품', '피곤', '지루'] },
  { emoji: '🤤', keywords: ['군침', '먹고싶다'] },
  { emoji: '😋', keywords: ['맛있다', '냠냠'] },
  { emoji: '🤪', keywords: ['엉뚱', '장난'] },
  { emoji: '😳', keywords: ['당황', '부끄러움'] },
  { emoji: '🫠', keywords: ['녹아내림', '무너짐'] },
  { emoji: '🫡', keywords: ['경례', '알겠습니다', '넵'] },
  { emoji: '🤫', keywords: ['쉿', '비밀'] },
  { emoji: '🤭', keywords: ['실수', '웃참'] },
  { emoji: '🥶', keywords: ['추움', '얼음'] },
  { emoji: '🥵', keywords: ['더움', '땀'] },
  { emoji: '😐', keywords: ['무표정', '뜨악'] },
  { emoji: '🙂', keywords: ['미소', '괜찮음'] },
  { emoji: '🫶', keywords: ['하트손', '사랑'] },

  // 제스처/손동작
  { emoji: '👌', keywords: ['오케이', '좋아'] },
  { emoji: '🤙', keywords: ['콜', '연락해'] },
  { emoji: '👊', keywords: ['주먹', '화이팅'] },
  { emoji: '✊', keywords: ['파이팅', '주먹'] },
  { emoji: '🤞', keywords: ['행운', '기원'] },
  { emoji: '👋', keywords: ['안녕', '인사'] },
  { emoji: '🖐️', keywords: ['하이파이브', '손바닥'] },

  // 업무/오피스
  { emoji: '💼', keywords: ['일', '업무', '가방'] },
  { emoji: '📅', keywords: ['일정', '캘린더'] },
  { emoji: '📌', keywords: ['고정', '중요'] },
  { emoji: '📝', keywords: ['메모', '작성'] },
  { emoji: '📊', keywords: ['통계', '그래프'] },
  { emoji: '💻', keywords: ['노트북', '작업'] },
  { emoji: '📈', keywords: ['상승', '성장'] },
  { emoji: '📉', keywords: ['하락', '감소'] },
  { emoji: '🗓️', keywords: ['달력', '스케줄'] },
  { emoji: '✏️', keywords: ['연필', '작성'] },
  { emoji: '📎', keywords: ['첨부', '클립'] },
  { emoji: '🖨️', keywords: ['인쇄', '프린터'] },
  { emoji: '📞', keywords: ['전화', '연락'] },
  { emoji: '✉️', keywords: ['메일', '편지'] },
  { emoji: '🔖', keywords: ['북마크', '태그'] },

  // 음식/음료 추가
  { emoji: '🍜', keywords: ['라면', '국수'] },
  { emoji: '🍔', keywords: ['햄버거'] },
  { emoji: '🍟', keywords: ['감자튀김'] },
  { emoji: '🌮', keywords: ['타코'] },
  { emoji: '🍰', keywords: ['케이크', '조각케이크'] },
  { emoji: '🍩', keywords: ['도넛'] },
  { emoji: '🍫', keywords: ['초콜릿'] },
  { emoji: '🍿', keywords: ['팝콘'] },
  { emoji: '🥤', keywords: ['음료', '콜라'] },
  { emoji: '🍎', keywords: ['사과'] },
  { emoji: '🍊', keywords: ['귤'] },
  { emoji: '🍇', keywords: ['포도'] },
  { emoji: '🍉', keywords: ['수박'] },
  { emoji: '🍓', keywords: ['딸기'] },
  { emoji: '🥗', keywords: ['샐러드'] },
  { emoji: '🍱', keywords: ['도시락'] },
  { emoji: '🍙', keywords: ['주먹밥'] },
  { emoji: '🍣', keywords: ['초밥'] },
  { emoji: '🍦', keywords: ['아이스크림'] },
  { emoji: '🧋', keywords: ['버블티'] },

  // 날씨/자연
  { emoji: '🌞', keywords: ['해', '맑음'] },
  { emoji: '🌧️', keywords: ['비'] },
  { emoji: '❄️', keywords: ['눈', '겨울'] },
  { emoji: '🌈', keywords: ['무지개'] },
  { emoji: '🌙', keywords: ['달', '밤'] },
  { emoji: '🌊', keywords: ['파도', '바다'] },
  { emoji: '🌸', keywords: ['벚꽃', '봄'] },
  { emoji: '🍀', keywords: ['네잎클로버', '행운'] },
  { emoji: '🌻', keywords: ['해바라기'] },
  { emoji: '🍁', keywords: ['단풍', '가을'] },

  // 이동수단
  { emoji: '🚗', keywords: ['자동차', '차'] },
  { emoji: '✈️', keywords: ['비행기', '여행'] },
  { emoji: '🚀', keywords: ['로켓', '출발'] },

  // 기호/사물
  { emoji: '💡', keywords: ['아이디어', '전구'] },
  { emoji: '✨', keywords: ['반짝', '잘했어'] },
  { emoji: '⚡', keywords: ['번개', '빠름'] },
  { emoji: '🎯', keywords: ['목표', '정확'] },
  { emoji: '🏆', keywords: ['트로피', '우승'] },
  { emoji: '🎁', keywords: ['선물'] },
  { emoji: '🔔', keywords: ['알림', '종'] },
  { emoji: '🔒', keywords: ['잠금', '비밀'] },
  { emoji: '🔑', keywords: ['열쇠', '해결'] },
  { emoji: '🕐', keywords: ['시간', '시계'] },
  { emoji: '📍', keywords: ['위치', '장소'] },
  { emoji: '🚨', keywords: ['경고', '긴급'] },
  { emoji: '🎈', keywords: ['풍선', '축하'] },

  // 동물 추가
  { emoji: '🐴', keywords: ['말', '동물'] },
  { emoji: '🐷', keywords: ['돼지', '동물'] },
  { emoji: '🐔', keywords: ['닭', '동물'] },
  { emoji: '🐢', keywords: ['거북이', '동물'] },
  { emoji: '🐙', keywords: ['문어', '동물'] },
  { emoji: '🦄', keywords: ['유니콘', '동물'] },
  { emoji: '🐦', keywords: ['새', '동물'] },
  { emoji: '🐝', keywords: ['벌', '동물'] },
  { emoji: '🦋', keywords: ['나비', '동물'] },
]
