// 반응 이모지 검색용 라이브러리. 각 이모지에 한글 키워드를 붙여서 검색 가능하게 한다.
// 기본으로 노출되는 이모지는 없다 — "+ 이모지"를 눌러 검색해서 고른 것만 그 자리에 하나씩 나타난다.

export type EmojiEntry = { emoji: string; keywords: string[] }

export const EMOJI_LIBRARY: EmojiEntry[] = [
  { emoji: '❤️', keywords: ['하트', '마음', '좋아요', '사랑'] },
  { emoji: '😂', keywords: ['웃음', 'ㅋㅋ', '폭소', '빵터짐'] },
  { emoji: '👍', keywords: ['좋아요', '따봉', '엄지'] },
  { emoji: '🎉', keywords: ['축하', '파티', '경축'] },
  { emoji: '🔥', keywords: ['불', '핫', '대박', '열정'] },
  { emoji: '👏', keywords: ['박수', '잘했어', '칭찬'] },
  { emoji: '🙌', keywords: ['만세', '축하', '환호'] },
  { emoji: '🙏', keywords: ['감사', '부탁', '기도'] },
  { emoji: '😮', keywords: ['놀람', '헐', '오'] },
  { emoji: '😢', keywords: ['슬픔', '눈물', '울음'] },
  { emoji: '😅', keywords: ['민망', '땀', '어색'] },
  { emoji: '🤔', keywords: ['고민', '생각', '음'] },
  { emoji: '😴', keywords: ['잠', '피곤', '졸림'] },
  { emoji: '🥳', keywords: ['파티', '생일', '축하'] },
  { emoji: '😎', keywords: ['쿨', '멋짐', '선글라스'] },
  { emoji: '💯', keywords: ['백점', '완벽', '만점'] },
  { emoji: '✅', keywords: ['체크', '완료', '확인'] },
  { emoji: '❌', keywords: ['엑스', '아니오', '취소'] },
  { emoji: '⭐', keywords: ['별', '최고', '스타'] },
  { emoji: '💪', keywords: ['파이팅', '근육', '힘내'] },
  { emoji: '🙄', keywords: ['어이없음', '눈굴림'] },
  { emoji: '😱', keywords: ['놀람', '충격', '헐'] },
  { emoji: '🤯', keywords: ['폭발', '대박', '멘붕'] },
  { emoji: '🥲', keywords: ['눈물', '웃음', '울먹'] },
  { emoji: '🤝', keywords: ['악수', '합의', '협업'] },
  { emoji: '✌️', keywords: ['브이', '평화', '손가락'] },
  { emoji: '🐾', keywords: ['발바닥', '동물', '고양이', '강아지'] },
  { emoji: '🐶', keywords: ['강아지', '개', '동물'] },
  { emoji: '🐱', keywords: ['고양이', '냥이', '동물'] },
  { emoji: '🐻', keywords: ['곰', '동물'] },
  { emoji: '🐼', keywords: ['판다', '동물'] },
  { emoji: '🐰', keywords: ['토끼', '동물'] },
  { emoji: '🦊', keywords: ['여우', '동물'] },
  { emoji: '🐯', keywords: ['호랑이', '동물'] },
  { emoji: '🐹', keywords: ['햄스터', '동물'] },
  { emoji: '🐮', keywords: ['소', '동물'] },
  { emoji: '🐨', keywords: ['코알라', '동물'] },
  { emoji: '🐧', keywords: ['펭귄', '동물'] },
  { emoji: '🦁', keywords: ['사자', '동물'] },
  { emoji: '🐸', keywords: ['개구리', '동물'] },
  { emoji: '☕', keywords: ['커피', '카페'] },
  { emoji: '🍕', keywords: ['피자', '음식'] },
  { emoji: '🍺', keywords: ['맥주', '술'] },
  { emoji: '🎂', keywords: ['케이크', '생일'] },
]
